### ISSUE TITLE
Finalize plugin API spec

### ISSUE THREAD

**Issue by mgartner** [calipersjs/calipers#36]
What functions will Calipers plugins need to provide? Is it just the `detect` and `measure` functions they currently expose, or does there need to be other functionality or is there a better naming schema?

Once this is finalized we can start building the plugins.

**Comment by borodean** [comment]
A Calipers format is an object which exposes `detect` and `measure` functions.

## `detect(buffer)`

Arguments:

1. `buffer (Buffer)`: first 16 bytes of a measured file.

Returns:

`(Boolean|Promise)`: either a measured file matches the format.

If a promise is returned, it should resolve to a corresponding boolean.

## `measure(path, fd)`

Arguments:

1. `path (String)`: a path to a measured file. It could be either absolute or relative.
2. `fd (Number)`: measured file descriptor.

Returns:

`(Object|Promise)`: measurements:
- `type (String)`: format name.
- `pages (Array of Objects)`: measurements for all of the file's pages. For non-paged files, it consists of a single element.
  - `width (Number)`: horizontal length of a page.
  - `height (Number)`: vertical length of a page.

If a promise is returned, it should resolve to a corresponding object.

**Comment by borodean** [comment]
As I understood, the `path` argument passed to the `measure` method is the same thing that is passed to the `measure` method of Calipers itself. Since all the operations where it is involved understand both relative and absolute paths the argument could be both kinds as well.

However, I think it is important to document this thing so developers would be aware it could be two kinds of things as it theoretically able to break something. There is also a solution to force-transform all the provided paths to absolute paths before being passed to a format.

**Comment by borodean** [comment]
Also, why does the object returned by `measure` contains `type`? Is it supposed to be a mime-type name or a measurer's name or something else?

**Comment by mgartner** [comment]
We've found it useful to get back the type of the file in our applications to know whether or not we want to convert. For example, if we allow users to upload PNG and JPEG, but want to store all images as JPEG, we can check the type and if it's a PNG, use ImageMagick to convert it to JPEG. I used all lowercase string names for the type just because I thought it was simplest.

**Comment by mgartner** [comment]
And regarding `path`, are you sure it currently works with relative paths?

**Comment by mgartner** [comment]
Closing as this has been finalized for 2.0.0.
